language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: qkdS7S8CaniUVYXYOobzfl2WCbFwXwamMGwO6TRkCCgIuqbJAk0iWdAkbfMFcH/x0KBhWPKg2HT1I7xH6AaihOJ3ncUK8bIY3u5No56lnJGjDhh7NH2fHRKEV66HsS60noh9fNp3ZOzc/TImJcVepSn1rdoaqHhaa0Sn7M+rLcBhwNjPl5hpdQTOV0MzySvVw3GuRpvMWZCjlh8qz9HjmlGveW2SNVhM86ODE4Z231MButqLNPo6uECu3M6QMVtQTIAqYBtco3ZJrzxsuGX8Oj/214AERb2Yh+i4K0HSLYJkzMvve6iSzp0FQl5DTZk9544BGW8PjRvGrHTRknpg4z74da2abkB1Z3Mke3gRr3hPjGJfUZKBsOIeXh/K8ee8G4po5rMW1z2zPQGnbwGPY2QXMMvKIsxMn6JuKPvfgtgVfOtfGXY9C65AHoXWBFU/VpNBB8FQp/VZnK0jd4zqhu8us5VJ6WQcO7mh2qbl4ViF6ftrZ6dbtcM2DFFhLN80yOW7ZlJUHhIRMaEpooeAzTgmMyPsz5MLpy/nQ33cqMJBYooe1Cu2050gcbR53mHEdjm5Hp5WyEPZkZTch0UxEJaq5D/mx2+NDPt5t+AU94FYlmraxaZ9MPdfP8rbnVsOgz0ndfwsv6C9YouTlJM7ikdoffsuFhLgEyZS2it7zcs=
  app: infinite-badlands-72488
  on:
    repo: F-Adam-B/CheeseHubServer
